name: Daily Stock Scraper

on:
  schedule:
    # Poniżej znajduje się wyrażenie cron. Uruchomi skrypt raz dziennie o 00:00 UTC.
    # Możesz zmienić harmonogram, jeśli chcesz.
    - cron: '20 21 * * *'
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    env:
      # ZMIENNA ŚRODOWISKOWA Z URL-em DO BAZY DANYCH
      # Wartość tej zmiennej musisz ustawić w "GitHub Secrets"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper script
        run: python scraper.py
